/*
 * This file is generated by jOOQ.
 */
package ege.bot.service.codegen.models.tables.references


import ege.bot.service.codegen.models.tables.Chat
import ege.bot.service.codegen.models.tables.ExamResult
import ege.bot.service.codegen.models.tables.Student



/**
 * Table with chats (e.g. users)
 */
val CHAT: Chat = Chat.CHAT

/**
 * Results table
 */
val EXAM_RESULT: ExamResult = ExamResult.EXAM_RESULT

/**
 * Students'es data
 */
val STUDENT: Student = Student.STUDENT
