/*
 * This file is generated by jOOQ.
 */
package ege.bot.service.codegen.models.sequences


import ege.bot.service.codegen.models.Results

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>results.student_id</code>
 */
val STUDENT_ID: Sequence<Long> = Internal.createSequence("student_id", Results.RESULTS, SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null)
