/*
 * This file is generated by jOOQ.
 */
package ege.bot.service.codegen.models.indexes


import ege.bot.service.codegen.models.tables.Student

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IX_STUDENT_YEAR: Index = Internal.createIndex(DSL.name("ix_student_year"), Student.STUDENT, arrayOf(Student.STUDENT.EXAM_YEAR), false)
