/*
 * This file is generated by jOOQ.
 */
package ege.bot.service.codegen.models.tables.records


import ege.bot.service.codegen.models.tables.ChatPolls

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * Information about active polls
 */
@Suppress("UNCHECKED_CAST")
open class ChatPollsRecord() : UpdatableRecordImpl<ChatPollsRecord>(ChatPolls.CHAT_POLLS) {

    open var pollId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var chatId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var messageId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised ChatPollsRecord
     */
    constructor(pollId: Long? = null, chatId: Long? = null, messageId: Long? = null): this() {
        this.pollId = pollId
        this.chatId = chatId
        this.messageId = messageId
        resetChangedOnNotNull()
    }
}
