/*
 * This file is generated by jOOQ.
 */
package ege.bot.service.codegen.models.tables.records


import ege.bot.service.codegen.models.tables.Chat

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * Table with chats (e.g. users)
 */
@Suppress("UNCHECKED_CAST")
open class ChatRecord() : UpdatableRecordImpl<ChatRecord>(Chat.CHAT) {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var chatMode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var state: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised ChatRecord
     */
    constructor(id: Long? = null, chatMode: String? = null, state: String? = null): this() {
        this.id = id
        this.chatMode = chatMode
        this.state = state
        resetChangedOnNotNull()
    }
}
